### ISSUE TITLE
Plugin doesn't install with ios@5.0.0

### ISSUE THREAD

**Issue by RohanTalip** [ReallySmallSoftware/cordova-plugin-firebaseui-auth#8]
## Expected Behavior

Plugin should install without a problem using ios@5.0.0 as a Cordova platform.

## Actual Behavior

```
$ cordova plugin add cordova-plugin-firebaseui-auth --variable ANDROID_FIREBASE_CORE_VERSION=16.0.0     --variable ANDROID_FIREBASE_AUTH_VERSION=16.0.1    --variable ANDROID_PLAY_SERVICES_AUTH_VERSION=15.0.1    --variable ANDROID_FIREBASEUI_VERSION=3.3.1    --variable ANDROID_FACEBOOK_SDK_VERSION=4.31.0    --variable FACEBOOK_APPLICATION_ID=12345678    --variable FACEBOOK_DISPLAY_NAME="My application"    --variable REVERSED_CLIENT_ID="com.googleusercontent.apps.9999999999-xxxxxxxxxxxxxxxxxxxxxxxxxx"    --variable COLOR_PRIMARY="#ffffff"    --variable COLOR_DARK_PRIMARY="#555555"    --variable COLOR_LIGHT_PRIMARY="#aaaaaa"    --variable COLOR_ACCENT="#7C4DFF"    --variable COLOR_SECONDARY="#FFC107"    --variable COLOR_CONTROL="#ffffff"    --variable COLOR_BACKGROUND="#000000"
Installing "cordova-plugin-firebaseui-auth" for ios
Installing "cordova-plugin-android-fragmentactivity" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebaseui-auth': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/rohantalip/dev/cordova-test/hello/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
pod: Command failed with exit code 1
```

## Steps to Reproduce the Problem

```
$ mkdir cordova-test
$ cordova create hello com.example.hello HelloWorld
$ cd hello
```

Installation succeeds with version 4.5.4 of the iOS platform:
```
$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.example.hello
	Name: HelloWorld
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
```

An Android-specific plugin is also installed along with some detached HEAD git messages, but at least the plugin is installed:
```
$ cordova plugin add cordova-plugin-firebaseui-auth --variable ANDROID_FIREBASE_CORE_VERSION=16.0.0     --variable ANDROID_FIREBASE_AUTH_VERSION=16.0.1    --variable ANDROID_PLAY_SERVICES_AUTH_VERSION=15.0.1    --variable ANDROID_FIREBASEUI_VERSION=3.3.1    --variable ANDROID_FACEBOOK_SDK_VERSION=4.31.0    --variable FACEBOOK_APPLICATION_ID=12345678    --variable FACEBOOK_DISPLAY_NAME="My application"    --variable REVERSED_CLIENT_ID="com.googleusercontent.apps.9999999999-xxxxxxxxxxxxxxxxxxxxxxxxxx"    --variable COLOR_PRIMARY="#ffffff"    --variable COLOR_DARK_PRIMARY="#555555"    --variable COLOR_LIGHT_PRIMARY="#aaaaaa"    --variable COLOR_ACCENT="#7C4DFF"    --variable COLOR_SECONDARY="#FFC107"    --variable COLOR_CONTROL="#ffffff"    --variable COLOR_BACKGROUND="#000000"
Installing "cordova-plugin-firebaseui-auth" for ios
Installing "cordova-plugin-android-fragmentactivity" for ios
     Cloning into '/var/folders/6z/pjhh1g4n1cjg_5gjgphmx8s00000gn/T/d20190213-56729-1qcoii0'...

     Note: checking out '937788f6c31156113480e491bef4c5c7e04ea7d9'.
     

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

     Cloning into '/var/folders/6z/pjhh1g4n1cjg_5gjgphmx8s00000gn/T/d20190213-56729-qub5a2'...

     Note: checking out '937788f6c31156113480e491bef4c5c7e04ea7d9'.
     
     You are in 'detached HEAD' state. You can look around, make experimental

     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                    Dload  Upload   Total   Spent    Left  Speed
   
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100  6768  100  6768    0     0  19332      0 --:--:-- --:--:-- --:--:-- 19282

     Cloning into '/var/folders/6z/pjhh1g4n1cjg_5gjgphmx8s00000gn/T/d20190213-56729-1udfet6'...

     Note: checking out '3fd239124995e1f4321c185eed0141981341349f'.
     

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

     Cloning into '/var/folders/6z/pjhh1g4n1cjg_5gjgphmx8s00000gn/T/d20190213-56729-renwd1'...

     Note: checking out '3fd239124995e1f4321c185eed0141981341349f'.
     

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

     Cloning into '/var/folders/6z/pjhh1g4n1cjg_5gjgphmx8s00000gn/T/d20190213-56729-7oqvh4'...

     Note: checking out '2d01f774f301124e1530cc63421393f8be2e0b7c'.
     

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

Adding cordova-plugin-firebaseui-auth to package.json
Saved plugin info for "cordova-plugin-firebaseui-auth" to config.xml
```

Remove the plugin (so it can be reinstalled with ios@5.0.0) :
```
$ cordova plugin remove cordova-plugin-firebaseui-auth                                                                                                                                                                                                       Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-android-fragmentactivity from ios
Uninstalling cordova-plugin-firebaseui-auth from ios

[!] The Podfile does not contain any dependencies.

Removing "cordova-plugin-firebaseui-auth"
Removing plugin cordova-plugin-firebaseui-auth from config.xml file...
Removing cordova-plugin-firebaseui-auth from package.json
```

Remove ios@4.5.4 as a platform:
```
$ cordova platform remove ios
Removing platform ios from config.xml file...
Removing ios from cordova.platforms array in package.json
```

Add ios@5.0.0 as a platform:
```
$ cordova platform add ios@5.0.0
Using cordova-fetch for cordova-ios@5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.example.hello
	Name: HelloWorld
iOS project created with cordova-ios@5.0.0
Installing "cordova-plugin-whitelist" for ios
--save flag or autosave detected
Saving ios@~5.0.0 into config.xml file ...
```

```
$ cordova plugin add cordova-plugin-firebaseui-auth --variable ANDROID_FIREBASE_CORE_VERSION=16.0.0     --variable ANDROID_FIREBASE_AUTH_VERSION=16.0.1    --variable ANDROID_PLAY_SERVICES_AUTH_VERSION=15.0.1    --variable ANDROID_FIREBASEUI_VERSION=3.3.1    --variable ANDROID_FACEBOOK_SDK_VERSION=4.31.0    --variable FACEBOOK_APPLICATION_ID=12345678    --variable FACEBOOK_DISPLAY_NAME="My application"    --variable REVERSED_CLIENT_ID="com.googleusercontent.apps.9999999999-xxxxxxxxxxxxxxxxxxxxxxxxxx"    --variable COLOR_PRIMARY="#ffffff"    --variable COLOR_DARK_PRIMARY="#555555"    --variable COLOR_LIGHT_PRIMARY="#aaaaaa"    --variable COLOR_ACCENT="#7C4DFF"    --variable COLOR_SECONDARY="#FFC107"    --variable COLOR_CONTROL="#ffffff"    --variable COLOR_BACKGROUND="#000000"
Installing "cordova-plugin-firebaseui-auth" for ios
Installing "cordova-plugin-android-fragmentactivity" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebaseui-auth': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/rohantalip/dev/cordova-test/hello/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
pod: Command failed with exit code 1
```

## Specifications

  - Plugin version: 1.0.2
  - Framework: Cordova
  - Framework version: 8.1.1
  - Operating system: MacOS 10.13.6

**Comment by ReallySmallSoftware** [comment]
Thanks for the report. I will take a look when I can.

**Comment by ReallySmallSoftware** [comment]
Hopefully this is addressed with the latest version. It seems to work OK for me on ios@5.0.0, making sure cordova itself is version 9.0.0, else I had trouble.

**Comment by ReallySmallSoftware** [comment]
I haven't heard anything from the OP, and I believe this works now, so I am closing this issue.
